# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'SelfHosted-Test'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  resourceGroupName: 'rg-dev-rickyx'
  deploymentLocation: 'Central US'
  templateLocation: 'centralus'
  apiProject: 'SalesTracker.Api/SalesTracker.Api.csproj'
  webAppName: 'salestracker-api-app'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(deb09ec0-d58c-47c9-a1f3-49d2ed4098fc)'
    subscriptionId: 'deb09ec0-d58c-47c9-a1f3-49d2ed4098fc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(deploymentLocation)'
    templateLocation: 'Linked artifact'
    csmFile: 'SalesTracker.Api/main.bicep'
    overrideParameters: '-location "$(templateLocation)"'
    deploymentMode: 'Incremental'

- task: UseDotNet@2
  displayName: 'Install .NET SDK 9.x'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET projects'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy API to App Service'
  inputs:
    azureSubscription: 'Azure subscription 1(deb09ec0-d58c-47c9-a1f3-49d2ed4098fc)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/api/**/*.zip'
